### ISSUE TITLE
Config file for servers? It would be nice to pick and choose which arrow recipes are available for players.

### ISSUE THREAD

**Issue by Kholdster** [jhale1805/power-projectiles#13]
I love your plugin, and it works great on the latest 1.18.1 version of minecraft. However, I notice it doesn't come with a config file or any commands for configuring what the plugin provides.

It would be nice to be able to disable some of the arrows if we only want a certain selection available for players. Specifically, I'd like to disable the sniper arrow, as it seems a little too OP. It kinda negates regular arrows in almost all situations, especially considering how cheap it is to manufacture. 

Also, disabling the fire and tnt arrows would help prevent griefing.

Thanks for making a great plugin!

**Comment by thehale** [comment]
Great request. And I'm glad to hear that it works as expected on 1.18.1 (I haven't tested it there yet to double check for myself). 

I did write up a brief TODO along these lines in issue #6, I just haven't taken the time to implement it yet. Just to keep things organized, I'll close this issue as a duplicate since the simple mention of issue #6 will link this issue to it in a way that makes it easy to reference.

If you're feeling ambitious, feel free to try to make this addition yourself. I'm happy to guide and give feedback on any Pull Requests you make. If you don't know what a Pull Request is and are interested in trying to implement this feature, just let me know and I can point you to some good resources to start out!
