### ISSUE TITLE
How do you craft the power projectiles?

### ISSUE THREAD

**Issue by MrPlayInDirt** [jhale1805/power-projectiles#21]
i cant find the crafting recipe list for the plugin
can you please send me a list

**Comment by thehale** [comment]
Thanks for trying out the plugin!

The usage instructions are in the README: https://github.com/thehale/power-projectiles#crafting-and-use

> ## Crafting and Use
> As long as a player has gotten the Enchanter advancement, he/she can also see the recipe for all Power Projectiles. Each projectile's lore (the text below its name) contains instructions for how to use it.

I don't maintain a separate crafting list because the recipes can change. If you're comfortable with the code, you can look for the [`getRecipe` functions](https://github.com/search?q=repo%3Athehale%2Fpower-projectiles%20getRecipe&type=code) to see where the current recipes are defined.

For example, here's the recipe for the **Jail Arrow**. The `shape` of the recipe corresponds to the three rows in the crafting table.
https://github.com/thehale/power-projectiles/blob/34141c193812f8dc105d020ea76fc9052faf58f7/src/main/java/dev/jhale/powerprojectiles/powerarrow/JailArrow.java#L43-L52

The other type of recipe are shapeless recipes like the one for the **Swap Arrow**, where the specified ingredients have to be in the crafting table, but no specific order is required.
https://github.com/thehale/power-projectiles/blob/34141c193812f8dc105d020ea76fc9052faf58f7/src/main/java/dev/jhale/powerprojectiles/powerarrow/SwapArrow.java#L42-L51
